### ISSUE TITLE
конкурентность для лифтов

### ISSUE THREAD

**Issue by qpep3b** [ivanbukhtiyarov/elevators#22]
т.к. управляем лифтом через консольный клиент, то нужно выполнять операции жц лифта в неблокирующем режиме
есть несколько вариантов:
1. плодить для каждого лифта отдельный процесс - плохо, т.к. при большом количестве лифтов не напасёшься процессов
2. гонять каждый лифт в отдельном потоке - плохо, т.к. в питоне есть такая штука как GIL, и из-за него питонячий поток не является потоком в привычном понимании слова.
3. крутить лифты асинхронно - перемещения лифтов будут считаться тасками, выполняющимися в евент-лупе (https://docs.python.org/3/library/asyncio-task.html#creating-tasks)

Нужно провести какой-нибудь эксперимент с проверкой блокировки консольного i/o при асинхронности. При наличии i/o блокировок предлагаю использовать модель с потоками.

**Comment by qpep3b** [comment]
Ваня, исследуй теорию, которую я тебе в тг писал

**Comment by ivanbukhtiyarov** [comment]
@qpep3b После тестрирования возможностей мультипроцессинга, мультитрединга, asyncio, а также возможностей QTread, QSlider решено использовать внутренние возможности Qt для конкурентности лифтов.
