### ISSUE TITLE
кастомная конфигурация

### ISSUE THREAD

**Issue by qpep3b** [ivanbukhtiyarov/elevators#26]
сделать возможность чтения конфигурации при запуске cli
например 
 ```python main.py --config=conf.yaml```
должен читаться конфиг, и при наличии указанных числа этажей и пр. параметров, которые спрашиваются при запуске приложения, автоматически инициализировать их и не ожидать ввода от пользователя
конфигурацию вижу полезной для того, чтобы далее при росте числа параметров не запрашивать портянку всяких значений у пользователя
давайте условится, что формат конфига будет yaml как +- человекочитаемый (можно и toml если разработчик решится реализовать). JSON не предлагаю, т.к. там слишком много формальностей синтаксиса, да и руками JSON писать менее приятно, чем yaml

**Comment by alexander135** [comment]
Выполнено
