### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by qpep3b** [ivanbukhtiyarov/elevators#28]

**Comment by qpep3b** [comment]
текущее состояние
![image](https://user-images.githubusercontent.com/22394699/118379685-d83d5080-b5e4-11eb-8fcb-cc22cfdd2edf.png)

**Comment by qpep3b** [comment]
все кнопки, слайдеры, высота и ширина счиатются автоматически в зависимости от количества лифтов и этажей

**Comment by JellyBongo** [comment]
Как доделаю #31, можно будет отправлять запросы лифту через [command_processor.py](https://github.com/ivanbukhtiyarov/elevators/blob/dev/src/command_processor.py). Запрос — объект класса Command из command_processor с полями source, action, value и elevator_id. Для гуи, наверное, в качестве сурса лучше использовать Source.SYSTEM, потому что он поддерживает все возможные действия. Возможные сурсы и экшны расписаны в command_processor.py. Поле Elevator наверняка будет заменено на Operator, чтобы команды отправлялись оператору, а не кабине лифта.
Вот. Мне кажется, это удобно. Логика работы лифта будет отделена от гуи и логики обработки запросов.

**Comment by qpep3b** [comment]
> Как доделаю #31, можно будет отправлять запросы лифту через [command_processor.py](https://github.com/ivanbukhtiyarov/elevators/blob/dev/src/command_processor.py). Запрос — объект класса Command из command_processor с полями source, action, value и elevator_id. Для гуи, наверное, в качестве сурса лучше использовать Source.SYSTEM, потому что он поддерживает все возможные действия. Возможные сурсы и экшны расписаны в command_processor.py. Поле Elevator наверняка будет заменено на Operator, чтобы команды отправлялись оператору, а не кабине лифта.

не совсем понял про Source.SYSTEM, ближе к делу расскажешь
> Вот. Мне кажется, это удобно. Логика работы лифта будет отделена от гуи и логики обработки запросов.

Да, здраво

**Comment by qpep3b** [comment]
Добавил кнопки датчиков (сейчас просто пишут в консоль что такой-то датчик триггернулся)
![image](https://user-images.githubusercontent.com/22394699/119408906-26420a80-bcef-11eb-8c6d-5398c13af32d.png)

Добавил перемещение лифта к кликнутому этажу (на кнопку up или down) (сейчас просто выбирается рандомный лифт, и слайдер мгновенно перемещается на этаж)
![image](https://user-images.githubusercontent.com/22394699/119409024-58536c80-bcef-11eb-9ba0-36b8b54e6f9a.png)

**Comment by qpep3b** [comment]
добавил окно выбора этажа при остановке лифта. Сейчас по клике на кнопку этажа заглушка, пишущая в консоль номер этажа
![image](https://user-images.githubusercontent.com/22394699/119694628-10028e80-be56-11eb-9bea-37a6b501f3c6.png)
