### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by ivanbukhtiyarov** [ivanbukhtiyarov/elevators#3]
Init GitHub actions

**Comment by mikhinandrei** [comment]
i've alreaddy been working on it

**Comment by mikhinandrei** [comment]
tests running
https://github.com/ivanbukhtiyarov/elevators/runs/2273160159?check_suite_focus=true

**Comment by ivanbukhtiyarov** [comment]
@mikhinandrei I see, you can add an issue link to the commit name

**Comment by mikhinandrei** [comment]
@ivanbukhtiyarov what format?

**Comment by ivanbukhtiyarov** [comment]
> @ivanbukhtiyarov what format?

see above

**Comment by mikhinandrei** [comment]
enabled in `dev` branch
