### ISSUE TITLE
Описание плана сертификации: Раздел Сертификационные соображения

### ISSUE THREAD

**Issue by RustamSultanov** [ivanbukhtiyarov/elevators#52]
В данном разделе даётся итоговая сводка тех аспектов сертификационного базиса, включая методы и средства определения соответствия, которые связаны с сертификацией ПО.
Кроме того, в нём устанавливается уровень(ни) ПО и приводится его обоснование, полученное в процессе анализа безопасности системы, включая те, в которых указывается потенциальный вклад ПО в возникновение отказных состояний.

**Comment by RustamSultanov** [comment]
Нужно поправить форматирование в общем документе https://docs.google.com/document/d/1-f4OyG4iEGiRC79TylBU_lVhjAcABescsXdlQHUT2ow/edit#

**Comment by oneisglad** [comment]
Оформил документ к общему стилю
