### ISSUE TITLE
Описание плана сертификации: Раздел Описание жизненного цикла ПО

### ISSUE THREAD

**Issue by RustamSultanov** [ivanbukhtiyarov/elevators#53]
В данном разделе определяется жизненный цикл ПО, который предполагается реализовать, с кратким описанием каждого цикла и его процессов.
Более подробная информация по этим вопросам даётся в соответствующих планах создания ПО.
Данный раздел показывает, каким образом будут достигнуты цели каждого процесса жизненного цикла ПО, определяет участников работ по созданию ПО, определяет ответственных за организацию, за процессы жизненного цикла ПО и за взаимодействие с сертифицирующим органом.

**Comment by RustamSultanov** [comment]
Нужно поправить форматирование в общем документе https://docs.google.com/document/d/1-f4OyG4iEGiRC79TylBU_lVhjAcABescsXdlQHUT2ow/edit#

**Comment by oneisglad** [comment]
Привел документацию к общему стилю
