### ISSUE TITLE
Сертификация документа "Требования к ПО"

### ISSUE THREAD

**Issue by ivanbukhtiyarov** [ivanbukhtiyarov/elevators#60]

**Comment by cyberdile** [comment]
Направляю документ на проверку
[СпецификацияТребованийПО[v4].docx.pdf](https://github.com/ivanbukhtiyarov/elevators/files/7777387/v4.docx.pdf)

**Comment by cyberdile** [comment]
Направляю документ на проверку
[СпецификацияТребованийПО[v4].docx](https://github.com/ivanbukhtiyarov/elevators/files/7777389/v4.docx)

**Comment by RustamSultanov** [comment]
Документ принят сертификационным органом на проверку.

**Comment by krauseGL** [comment]
Комментарии:
1. Отсутствует детальное описание режимов работы
2. Абстрактное описание требований к обучению персонала (квалификации)
3. Требования к обнаружению отказов и мониторингу безопасности  неисчерпывающие, не пременимо для использования;
4. Качественно не влияет на сертификацию согласно плану, тем не менее имеется разумное суждение о необходимости систематизации требований по разбиению ПО, по взаимодействию выделенных компонентов ПО друг с другом и к уровням ПО для каждой части.

**Comment by RustamSultanov** [comment]
Дубликат https://github.com/ivanbukhtiyarov/elevators/issues/62 Закрываю задачу
