### ISSUE TITLE
RI-04-02: Реализовать класс Elevator

### ISSUE THREAD

**Issue by JellyBongo** [ivanbukhtiyarov/elevators#7]
Реализовать класс Elevator в соответствии с RI-04-02. Класс должен отвечать требованиям к интерфейсу ILift, описанному в документации. ILift переименован в Elevator, потому что pep. 

[Спецификация требований](https://drive.google.com/drive/folders/10XZ8vTVIj6Tz8zw37J_XzLmv1JLv0vI8?usp=sharing).

**Comment by mikhinandrei** [comment]
сначала необходимо реализовать очередь движения лифта
https://github.com/ivanbukhtiyarov/elevators/issues/10

**Comment by mikhinandrei** [comment]
отдельная подзадача:
https://github.com/ivanbukhtiyarov/elevators/issues/10

**Comment by mikhinandrei** [comment]
завёл ветку RI-04-02, в ней добавил тесты для подзадачи https://github.com/ivanbukhtiyarov/elevators/issues/10

**Comment by JellyBongo** [comment]
Merged as https://github.com/ivanbukhtiyarov/elevators/pull/30
