### ISSUE TITLE
RI-04-03: Реализовать класс Operator

### ISSUE THREAD

**Issue by JellyBongo** [ivanbukhtiyarov/elevators#8]
Реализовать класс Operator в соответствии с пунктом RI-04-03 спецификации требований.

[Спецификация требований](https://drive.google.com/drive/folders/10XZ8vTVIj6Tz8zw37J_XzLmv1JLv0vI8?usp=sharing).

**Comment by mikhinandrei** [comment]
вообще, кажется, для начальных условий (одного лифта) можно обойтись и без оператора
