### ISSUE TITLE
RI-04-04: Реализовать датчики и кнопки

### ISSUE THREAD

**Issue by JellyBongo** [ivanbukhtiyarov/elevators#9]
Модули сенсоров (датчиков) и кнопок лежат в директориях elevators/src/sensors и elevators/src/buttons. Необходимо реализовать соответствующие классы, руководствуясь RI-04-04 спецификации требований.

Придумать базовый класс вместо интерфейса ISensor (и, наверное, IButton), от которого будут наследоваться классы датчиков и кнопок.

Пункт про ссылки на экземпляры ILift (Elevator) и IOperator (Operator) выглядит, как дичь. Кажется, логичнее привязать датчики к кабине, а не кабину к датчикам. Пока сделать так, как в документации, но на следующем синке это надо будет обсудить.

[Спецификация требований](https://drive.google.com/drive/folders/10XZ8vTVIj6Tz8zw37J_XzLmv1JLv0vI8?usp=sharing)

**Comment by mikhinandrei** [comment]
базовые абстрактные классы уже есть
https://github.com/ivanbukhtiyarov/elevators/blob/dev/src/buttons/abstract_button.py
https://github.com/ivanbukhtiyarov/elevators/blob/dev/src/sensors/abstract_sensor.py

**Comment by mikhinandrei** [comment]
про привязку к кабине согласен, потому что датчики и кнопки управляют лифтом, а не лифт кнопками и датчиками
